### ISSUE TITLE
Why doesn't it support nested selectors?

### ISSUE THREAD

**Issue by frontend-3** [xi/stylelint-selector-pattern#1] opened 2017-12-16 15:10 UTC
Hi! This is a wonderful plugin, I was wondering why it complains about nested selectors like:
`.Component .Component-subComponent` 

Thanks in advance.

**Comment by xi** [comment] 2017-12-16 19:22
That should depend on the pattern you are using. Can you provide your config?

Note that none of the presets allows descendent combinators (aka nested selectors) because they are considered a bad practice by many. But of course you can define your own pattern.

**Edit**: Maybe to answer your question: `.Component .Component-subComponent` is considered a single selector that happens to consist of two class selectors combined with a descendant combinator. I do not plan to support matching individual parts of a selector.

**Comment by xi** [comment] 2018-05-03 16:16
Closing as everything works as intended.

**Closed as completed by xi** 2018-05-03 16:16 UTC
